// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {store} from '../models';
import {model} from '../models';
import {context} from '../models';

export function AddTags(arg1:Array<string>,arg2:Array<string>):Promise<Array<app.TagEditResult>>;

export function AppendTagToQuery(arg1:string,arg2:string):Promise<string>;

export function Backlinks(arg1:string):Promise<Array<store.Backlink>>;

export function Entry(arg1:string):Promise<model.Entry>;

export function MarkdownSource(arg1:string):Promise<string>;

export function OpenFolder(arg1:string):Promise<void>;

export function RemoveTags(arg1:Array<string>,arg2:Array<string>):Promise<Array<app.TagEditResult>>;

export function ReplaceTags(arg1:Array<string>,arg2:Array<string>):Promise<Array<app.TagEditResult>>;

export function Search(arg1:store.SearchOptions):Promise<store.Result>;

export function SelectFolder():Promise<string>;

export function SetTags(arg1:string,arg2:Array<string>):Promise<app.TagEditResult>;

export function Startup(arg1:context.Context):Promise<void>;

export function Status():Promise<app.Status>;

export function Tags(arg1:string,arg2:number):Promise<Array<store.TagSuggestion>>;
