// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {settings} from '../models';
import {linkcard} from '../models';
import {store} from '../models';
import {context} from '../models';
import {app} from '../models';

export function CancelLoadMore():Promise<void>;

export function CreatePage(arg1:string):Promise<boolean>;

export function Entry(arg1:string):Promise<model.Entry>;

export function FetchCloudEntry(arg1:string):Promise<model.Entry>;

export function GetSettings():Promise<settings.Settings>;

export function LinkPreview(arg1:string):Promise<linkcard.Preview>;

export function LinkedPage(arg1:string,arg2:string):Promise<model.Entry>;

export function LoadMore(arg1:boolean):Promise<void>;

export function MarkdownSource(arg1:string):Promise<string>;

export function OpenFolder(arg1:string):Promise<void>;

export function OpenInEditor(arg1:string):Promise<void>;

export function OpenStartupFolder(arg1:string):Promise<void>;

export function RelatedPages(arg1:string):Promise<store.Related>;

export function SaveSettings(arg1:settings.Settings):Promise<settings.Settings>;

export function Search(arg1:store.SearchOptions):Promise<store.Result>;

export function SelectFolder():Promise<string>;

export function SetPinned(arg1:string,arg2:boolean):Promise<void>;

export function SettingsPath():Promise<string>;

export function Startup(arg1:context.Context):Promise<void>;

export function Status():Promise<app.Status>;

export function TagPage(arg1:string):Promise<model.Entry>;

export function TakeStartupWarnings():Promise<Array<string>>;
