// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelLoadMore() {
  return window['go']['app']['App']['CancelLoadMore']();
}

export function CreatePage(arg1) {
  return window['go']['app']['App']['CreatePage'](arg1);
}

export function Entry(arg1) {
  return window['go']['app']['App']['Entry'](arg1);
}

export function FetchCloudEntry(arg1) {
  return window['go']['app']['App']['FetchCloudEntry'](arg1);
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function LinkPreview(arg1) {
  return window['go']['app']['App']['LinkPreview'](arg1);
}

export function LinkedPage(arg1, arg2) {
  return window['go']['app']['App']['LinkedPage'](arg1, arg2);
}

export function LoadMore(arg1) {
  return window['go']['app']['App']['LoadMore'](arg1);
}

export function MarkdownSource(arg1) {
  return window['go']['app']['App']['MarkdownSource'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['app']['App']['OpenFolder'](arg1);
}

export function OpenInEditor(arg1) {
  return window['go']['app']['App']['OpenInEditor'](arg1);
}

export function OpenStartupFolder(arg1) {
  return window['go']['app']['App']['OpenStartupFolder'](arg1);
}

export function RelatedPages(arg1) {
  return window['go']['app']['App']['RelatedPages'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['app']['App']['SaveSettings'](arg1);
}

export function Search(arg1) {
  return window['go']['app']['App']['Search'](arg1);
}

export function SelectFolder() {
  return window['go']['app']['App']['SelectFolder']();
}

export function SetPinned(arg1, arg2) {
  return window['go']['app']['App']['SetPinned'](arg1, arg2);
}

export function SettingsPath() {
  return window['go']['app']['App']['SettingsPath']();
}

export function Startup(arg1) {
  return window['go']['app']['App']['Startup'](arg1);
}

export function Status() {
  return window['go']['app']['App']['Status']();
}

export function TagPage(arg1) {
  return window['go']['app']['App']['TagPage'](arg1);
}

export function TakeStartupWarnings() {
  return window['go']['app']['App']['TakeStartupWarnings']();
}
